import { markdownHeadings, mergeRecognizedStatement, recognizedSectionTitles, type MarkdownHeading, type RecognizedSection, type RecognizedSectionKind } from './statementRecognition.ts';

/** Remove actual image references while keeping image-like strings in sample data. */
function withoutImages(value: string): string {
  let fence: { marker: string; length: number } | undefined;
  return value.split(/\r?\n/).map(line => {
    const marker = line.match(/^\s{0,3}(`{3,}|~{3,})/);
    if (marker) {
      if (!fence) fence = { marker: marker[1][0], length: marker[1].length };
      else if (marker[1][0] === fence.marker && marker[1].length >= fence.length) fence = undefined;
      return line;
    }
    if (fence) return line;
    if (/^\s{0,3}\[[^\]]+\]:\s*<?\/api\/images\//.test(line)) return '';
    return line.replace(/!\[(?:\\.|[^\]\\])*\](?:\((?:\\.|[^)\n])*\)|\[[^\]\n]*\])/g, '');
  }).join('\n');
}

/** Only the problem's text goes to AI; independent sections stay in the source. */
export function prepareAiStatement(value: string): string {
  const headings = markdownHeadings(value);
  const excluded: {start: number; end: number}[] = [];
  for (let index = 0; index < headings.length; index++) {
    const heading = headings[index];
    if (heading.kind || heading.level > 2 || excluded.some(range => heading.start < range.end)) continue;
    const next = headings.slice(index + 1).find(item => item.level <= heading.level);
    excluded.push({start: heading.start, end: next?.start ?? value.length});
  }
  let source = value;
  for (const range of excluded.reverse()) source = source.slice(0, range.start) + source.slice(range.end);
  return withoutImages(source).trim();
}

function unwrapMarkdown(value: string): string {
  const text = value.trim();
  const wrapper = text.match(/^(`{3,}|~{3,})(?:markdown|md)?\s*\r?\n([\s\S]*)\r?\n\1\s*$/i);
  return wrapper && /^\s*#{1,6}\s/m.test(wrapper[2]) ? wrapper[2].trim() : text;
}

/** Parse Markdown by section boundaries, never treating fenced data as headings. */
export function parseAiStatement(value: string): RecognizedSection[] {
  const text = withoutImages(unwrapMarkdown(value));
  const headings = markdownHeadings(text);
  if (!headings.length) return [];
  const base: MarkdownHeading[] = [];
  let sampleLevel: number | undefined;
  for (const heading of headings) {
    if (sampleLevel !== undefined && heading.level > sampleLevel) continue;
    if (sampleLevel !== undefined && heading.level <= sampleLevel) sampleLevel = undefined;
    if (!heading.kind) continue;
    base.push(heading);
    if (heading.kind === 'samples') sampleLevel = heading.level;
  }
  const sections = new Map<RecognizedSectionKind, RecognizedSection>();
  const add = (kind: RecognizedSectionKind, content: string) => {
    const body = content.trim();
    if (!body) return;
    const prior = sections.get(kind);
    if (prior) { if (kind !== 'title') prior.content += `\n\n${body}`; }
    else sections.set(kind, {id: `ai-${kind}`, kind, title: recognizedSectionTitles[kind], content: body, regions: []});
  };
  base.forEach((heading, index) => {
    const end = base[index + 1]?.start ?? text.length;
    // Don't absorb unrelated top-level sections generated by the provider.
    const unknown = headings.find(item => item.start > heading.start && item.start < end && !item.kind && item.level <= heading.level);
    const body = text.slice(heading.lineEnd, unknown?.start ?? end).trim();
    if (heading.kind === 'title') {
      const generic = /^(?:题目标题|题目名称|title|problem\s*title)[:：]?$/i.test(heading.label);
      if (generic) add('title', body);
      else { add('title', heading.label); if (body) add('description', body); }
    } else if (heading.kind === 'samples') {
      const generic = /^(?:样例|测试样例|输入输出样例|samples?|examples?)[:：]?$/i.test(heading.label.replace(/\s/g, ''));
      add('samples', generic ? body : `### ${heading.label}\n\n${body}`);
    } else add(heading.kind!, body);
  });
  return [...sections.values()];
}

/** A missing AI section cannot erase existing text, screenshots or private notes. */
export function applyAiStatement(original: string, sections: RecognizedSection[]): string {
  const valid = sections.filter(section => section.content.trim()).map(section => ({...section, content: withoutImages(section.content).trim()}));
  return valid.length ? mergeRecognizedStatement(original, valid) : original;
}
