server.address=127.0.0.1
server.port=0
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=10s
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=11MB
spring.jackson.default-property-inclusion=always
spring.mvc.async.request-timeout=0
mybatis.configuration.map-underscore-to-camel-case=true
logging.level.root=WARN
logging.level.com.duipai=INFO
spring.main.banner-mode=off
